name: cgi_versoes_helper
description: Pacote para controle de versão e notas de versão para os Apps da CGI Software.
version: 1.0.4
homepage: http://www.webcgi.com.br
repository: https://github.com/omateuscastro/cgi_versoes_helper

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  package_info: ^0.4.0+18
  url_launcher: ^5.4.7
  cloud_firestore: ^0.12.11

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # plugin:
  #   androidPackage: io.github.omateuscastro.cgi_versoes_helper
  #   pluginClass: CGIVersoesHelperPlugin
